[build]
  base = "client"
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  REACT_APP_API_URL = "http://13.221.210.59:3000"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200