[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "http://13.221.210.59:3000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200